<br /><br />
<div id="view-content">
	<p>Are you sure that you want to delete
		'<?php echo $this->guestbook->getFirstname(); ?> 
		<?php echo $this->guestbook->getLastname(); ?>'?
	</p>
	<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
		<div>
			<input type="hidden" name="id" value="<?php echo $this->guestbook->getId(); ?>" />
			<input type="submit" name="del" value="Yes" />
			<input type="submit" name="cancel" value="No" />
		</div>
	</form>
</div>