<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Test Task Application</title>
  <?php echo $this->headLink()->appendStylesheet('/media/css/global.css') ?>
  <?php echo $this->jQuery()
	->setVersion('1.5.1')
	->setUiVersion('1.8.11')
	->enable()
	->uiEnable(); ?>
  <?php echo $this->headScript()->appendFile('/media/js/main.js') ?>
</head>
<body>
<div id="header">
    <div id="header-logo">
        <b><a href="<?php echo $this->url(
			array('controller'=>'index'),
            'default',
            true); ?>">ZF Test Task Application</a></b>
    </div>
</div>
 
<?php echo $this->layout()->content ?>
 
</body>
</html>